// web/src/pages/LibraryPage.vue
<template>
  <div class="page-library">
    <!-- Page Header -->
    <header class="page-header">
      <div class="header-left">
        <h1 class="page-title">我的书架</h1>
        <span v-if="!loading" class="book-count">{{ total }} 本书籍</span>
      </div>
      <div class="header-right">
        <div class="search-box">
          <Search :size="18" class="search-icon" />
          <input
            v-model="searchQuery"
            type="text"
            placeholder="搜索书籍..."
            @input="handleSearch"
          />
        </div>
        <div class="view-toggle">
          <button
            :class="['toggle-btn', { active: viewMode === 'grid' }]"
            @click="viewMode = 'grid'"
          >
            <Grid3x3 :size="16" />
          </button>
          <button
            :class="['toggle-btn', { active: viewMode === 'list' }]"
            @click="viewMode = 'list'"
          >
            <List :size="16" />
          </button>
        </div>
        <Button variant="primary" @click="showCreateModal = true">
          <Plus :size="18" />
          新建书籍
        </Button>
      </div>
    </header>

    <!-- Filter Bar -->
    <div class="filter-bar">
      <button
        v-for="filter in filters"
        :key="filter.value"
        :class="['filter-chip', { active: currentFilter === filter.value }]"
        @click="handleFilterChange(filter.value)"
      >
        {{ filter.label }}
      </button>
    </div>

    <!-- Loading State -->
    <div v-if="loading" class="books-grid">
      <SkeletonCard v-for="i in 6" :key="i" />
    </div>

    <!-- Empty State -->
    <EmptyState
      v-else-if="books.length === 0"
      :icon="Library"
      title="还没有书籍"
      description="开始创建你的第一本数字书籍"
    >
      <Button variant="primary" @click="showCreateModal = true">
        <Plus :size="18" />
        创建书籍
      </Button>
    </EmptyState>

    <!-- Books Grid -->
    <div v-else :class="['books-grid', `books-grid-${viewMode}`]">
      <BookCard
        v-for="book in books"
        :key="book.id"
        :book="book"
        @click="handleBookClick"
      />
    </div>

    <!-- Pagination -->
    <div v-if="totalPages > 1" class="pagination">
      <Button
        variant="secondary"
        :disabled="currentPage === 1"
        @click="goToPage(currentPage - 1)"
      >
        上一页
      </Button>
      <span class="pagination-info">第 {{ currentPage }} / {{ totalPages }} 页</span>
      <Button
        variant="secondary"
        :disabled="currentPage === totalPages"
        @click="goToPage(currentPage + 1)"
      >
        下一页
      </Button>
    </div>

    <!-- Create Book Modal -->
    <Modal v-model="showCreateModal" title="创建新书籍" @close="handleModalClose">
      <form @submit.prevent="handleCreateBook">
        <Input
          v-model="newBook.title"
          label="书名"
          placeholder="输入书籍标题"
          required
        />
        <Input
          v-model="newBook.author"
          label="作者"
          placeholder="输入作者姓名"
          required
        />
        <Input
          v-model="newBook.isbn"
          label="ISBN (可选)"
          placeholder="输入ISBN编号"
        />
        <Input
          v-model.number="newBook.totalPages"
          type="number"
          label="预计总页数"
          placeholder="输入预计页数"
          required
        />
      </form>
      <template #footer>
        <Button variant="secondary" @click="showCreateModal = false">取消</Button>
        <Button variant="primary" :loading="creating" @click="handleCreateBook">
          创建书籍
        </Button>
      </template>
    </Modal>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useBooksStore } from '@/stores/books'
import { useToastStore } from '@/stores/toast'
import { Search, Grid3x3, List, Plus, Library } from 'lucide-vue-next'
import Button from '@/components/ui/Button.vue'
import Input from '@/components/ui/Input.vue'
import Modal from '@/components/ui/Modal.vue'
import BookCard from '@/components/ui/BookCard.vue'
import EmptyState from '@/components/ui/EmptyState.vue'
import SkeletonCard from '@/components/ui/SkeletonCard.vue'
import type { Book, BookStatus } from '@/types'

const router = useRouter()
const booksStore = useBooksStore()
const toastStore = useToastStore()

const viewMode = ref<'grid' | 'list'>('grid')
const searchQuery = ref('')
const currentFilter = ref<BookStatus | 'all'>('all')
const showCreateModal = ref(false)
const creating = ref(false)

const newBook = ref<Partial<Book>>({
  title: '',
  author: '',
  isbn: '',
  totalPages: 100,
  uploadedPages: 0,
  status: 'draft',
})

const books = computed(() => booksStore.books)
const loading = computed(() => booksStore.loading)
const total = computed(() => booksStore.total)
const currentPage = computed(() => booksStore.query.page || 1)
const pageSize = computed(() => booksStore.query.pageSize || 12)
const totalPages = computed(() => Math.ceil(total.value / pageSize.value))

const filters = [
  { label: '全部', value: 'all' as const },
  { label: '草稿', value: 'draft' as const },
  { label: '上传中', value: 'uploading' as const },
  { label: '处理中', value: 'processing' as const },
  { label: '已完成', value: 'completed' as const },
]

onMounted(() => {
  booksStore.fetchBooks()
})

const handleSearch = (event: Event) => {
  const target = event.target as HTMLInputElement
  booksStore.setSearch(target.value)
}

const handleFilterChange = (filter: BookStatus | 'all') => {
  currentFilter.value = filter
  booksStore.setFilter(filter)
}

const handleBookClick = (book: Book) => {
  router.push(`/book/${book.id}`)
}

const handleCreateBook = async () => {
  if (!newBook.value.title || !newBook.value.author || !newBook.value.totalPages) {
    toastStore.warning('请填写所有必填字段')
    return
  }

  creating.value = true

  const created = await booksStore.createBook({
    ...newBook.value,
  } as Omit<Book, 'id' | 'createdAt' | 'updatedAt'>)

  creating.value = false

  if (created) {
    toastStore.success('书籍创建成功')
    showCreateModal.value = false
    // Reset form
    newBook.value = {
      title: '',
      author: '',
      isbn: '',
      totalPages: 100,
      uploadedPages: 0,
      status: 'draft',
    }
    // Navigate to upload page
    router.push(`/upload/${created.id}`)
  } else {
    toastStore.error('创建失败，请重试')
  }
}

const handleModalClose = () => {
  newBook.value = {
    title: '',
    author: '',
    isbn: '',
    totalPages: 100,
    uploadedPages: 0,
    status: 'draft',
  }
}

const goToPage = (page: number) => {
  booksStore.setPage(page)
}
</script>

<style scoped>
.page-library {
  padding: var(--space-8);
  max-width: var(--content-max-width);
  margin: 0 auto;
}

.page-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: var(--space-6);
  gap: var(--space-4);
}

.header-left {
  display: flex;
  align-items: baseline;
  gap: var(--space-3);
}

.page-title {
  font-size: var(--text-4xl);
  font-weight: var(--font-weight-bold);
  color: var(--text-primary);
}

.book-count {
  font-size: var(--text-base);
  color: var(--text-secondary);
}

.header-right {
  display: flex;
  align-items: center;
  gap: var(--space-3);
}

.search-box {
  position: relative;
}

.search-icon {
  position: absolute;
  left: var(--space-3);
  top: 50%;
  transform: translateY(-50%);
  color: var(--text-secondary);
  pointer-events: none;
}

.search-box input {
  width: 280px;
  padding: var(--space-3) var(--space-4) var(--space-3) var(--space-10);
  font-size: var(--text-base);
  color: var(--text-primary);
  background: var(--bg-elevated);
  border: 1px solid var(--border-medium);
  border-radius: var(--radius-md);
  transition: all var(--duration-fast) var(--ease-out);
}

.search-box input:focus {
  outline: none;
  border-color: var(--color-accent);
  box-shadow: var(--shadow-focus);
}

.view-toggle {
  display: flex;
  background: var(--bg-secondary);
  border-radius: var(--radius-md);
  padding: var(--space-1);
}

.toggle-btn {
  padding: var(--space-2) var(--space-3);
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--text-secondary);
  background: transparent;
  border: none;
  border-radius: var(--radius-sm);
  transition: all var(--duration-fast) var(--ease-out);
  cursor: pointer;
}

.toggle-btn.active {
  background: var(--bg-elevated);
  color: var(--text-primary);
  box-shadow: var(--shadow-sm);
}

.filter-bar {
  display: flex;
  gap: var(--space-2);
  margin-bottom: var(--space-6);
  overflow-x: auto;
  -webkit-overflow-scrolling: touch;
}

.filter-chip {
  padding: var(--space-2) var(--space-4);
  font-size: var(--text-sm);
  font-weight: var(--font-weight-medium);
  color: var(--text-secondary);
  background: var(--bg-secondary);
  border: none;
  border-radius: var(--radius-full);
  white-space: nowrap;
  cursor: pointer;
  transition: all var(--duration-fast) var(--ease-out);
}

.filter-chip:hover {
  background: var(--bg-tertiary);
  color: var(--text-primary);
}

.filter-chip.active {
  background: var(--color-accent);
  color: white;
}

.books-grid {
  display: grid;
  gap: var(--space-5);
}

.books-grid-grid {
  grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
}

.books-grid-list {
  grid-template-columns: 1fr;
}

.pagination {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: var(--space-4);
  margin-top: var(--space-8);
}

.pagination-info {
  font-size: var(--text-sm);
  color: var(--text-secondary);
}

@media (max-width: 768px) {
  .page-library {
    padding: var(--space-4);
  }

  .page-header {
    flex-direction: column;
    align-items: stretch;
  }

  .header-right {
    flex-direction: column;
  }

  .search-box input {
    width: 100%;
  }

  .books-grid-grid {
    grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
    gap: var(--space-3);
  }

  .filter-bar {
    padding-bottom: var(--space-2);
  }
}
</style>

// web/src/features/library/pages/LibraryPage/LibraryPage.tsx
import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { booksApi } from '@/features/library/api'
import { useToastStore } from '@/shared/stores/toast'
import type { Book, BookStatus } from '@/features/library/types'
import { Search, Grid3x3, List, Plus, BookOpen, Library as LibraryIcon } from 'lucide-react'
import './LibraryPage.css'

const STATUS_LABELS: Record<BookStatus, string> = {
  draft: '草稿',
  uploading: '上传中',
  processing: '处理中',
  completed: '已完成',
}

const FILTERS: { label: string; value: BookStatus | 'all' }[] = [
  { label: '全部', value: 'all' },
  { label: '草稿', value: 'draft' },
  { label: '上传中', value: 'uploading' },
  { label: '处理中', value: 'processing' },
  { label: '已完成', value: 'completed' },
]

export default function LibraryPage() {
  const navigate = useNavigate()
  const toast = useToastStore(s => s.add)

  const [books, setBooks] = useState<Book[]>([])
  const [total, setTotal] = useState(0)
  const [loading, setLoading] = useState(true)
  const [searchQuery, setSearchQuery] = useState('')
  const [currentFilter, setCurrentFilter] = useState<BookStatus | 'all'>('all')
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid')
  const [currentPage, setCurrentPage] = useState(1)
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [creating, setCreating] = useState(false)
  const [newBook, setNewBook] = useState({ title: '', author: '', isbn: '', totalPages: 100 })
  const pageSize = 12

  const totalPages = Math.ceil(total / pageSize)

  useEffect(() => { fetchBooks() }, [currentPage, currentFilter, searchQuery])

  const fetchBooks = async () => {
    setLoading(true)
    try {
      const res = await booksApi.list({ page: currentPage, pageSize, filter: currentFilter === 'all' ? undefined : currentFilter, search: searchQuery || undefined })
      setBooks(res.items || [])
      setTotal(res.total || 0)
    } catch {
      setBooks([])
      setTotal(0)
    } finally {
      setLoading(false)
    }
  }

  const handleSearch = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchQuery(e.target.value)
    setCurrentPage(1)
  }

  const handleFilterChange = (filter: BookStatus | 'all') => {
    setCurrentFilter(filter)
    setCurrentPage(1)
  }

  const handleCreateBook = async () => {
    if (!newBook.title || !newBook.author || !newBook.totalPages) {
      toast('warning', '请填写所有必填字段')
      return
    }
    setCreating(true)
    try {
      const created = await booksApi.create({ title: newBook.title, author: newBook.author, isbn: newBook.isbn, pages: newBook.totalPages })
      if (created) {
        toast('success', '书籍创建成功')
        setShowCreateModal(false)
        setNewBook({ title: '', author: '', isbn: '', totalPages: 100 })
        navigate(`/upload/${created.id}`)
      }
    } catch {
      toast('error', '创建失败，请重试')
    } finally {
      setCreating(false)
    }
  }

  return (
    <div className="page-library">
      {/* Page Header */}
      <header className="page-header">
        <div className="header-left">
          <h1 className="page-title">我的书架</h1>
          {!loading && <span className="book-count">{total} 本书籍</span>}
        </div>
        <div className="header-right">
          <div className="search-box">
            <Search size={18} className="search-icon" />
            <input type="text" placeholder="搜索书籍..." value={searchQuery} onChange={handleSearch} />
          </div>
          <div className="view-toggle">
            <button className={`toggle-btn ${viewMode === 'grid' ? 'active' : ''}`} onClick={() => setViewMode('grid')}>
              <Grid3x3 size={16} />
            </button>
            <button className={`toggle-btn ${viewMode === 'list' ? 'active' : ''}`} onClick={() => setViewMode('list')}>
              <List size={16} />
            </button>
          </div>
          <button className="btn-primary" onClick={() => setShowCreateModal(true)}>
            <Plus size={18} />
            <span>新建书籍</span>
          </button>
        </div>
      </header>

      {/* Filter Bar */}
      <div className="filter-bar">
        {FILTERS.map(f => (
          <button key={f.value} className={`filter-chip ${currentFilter === f.value ? 'active' : ''}`} onClick={() => handleFilterChange(f.value)}>
            {f.label}
          </button>
        ))}
      </div>

      {/* Loading Skeleton */}
      {loading && (
        <div className={`books-grid books-grid-${viewMode}`}>
          {Array.from({ length: 6 }).map((_, i) => (
            <div key={i} className="skeleton-card">
              <div className="skeleton-cover" />
              <div className="skeleton-title" />
              <div className="skeleton-author" />
            </div>
          ))}
        </div>
      )}

      {/* Empty State */}
      {!loading && books.length === 0 && (
        <div className="empty-state">
          <LibraryIcon size={64} className="empty-icon" />
          <h2 className="empty-title">还没有书籍</h2>
          <p className="empty-description">开始创建你的第一本数字书籍</p>
          <button className="btn-primary" onClick={() => setShowCreateModal(true)}>
            <Plus size={18} />
            <span>创建书籍</span>
          </button>
        </div>
      )}

      {/* Books Grid */}
      {!loading && books.length > 0 && (
        <div className={`books-grid books-grid-${viewMode}`}>
          {books.map(book => (
            <div key={book.id} className="book-card" onClick={() => navigate(`/book/${book.id}`)}>
              <div className="book-card-cover">
                {book.cover ? (
                  <img src={book.cover} alt={book.title} />
                ) : (
                  <div className="book-cover-placeholder">
                    <BookOpen size={32} />
                  </div>
                )}
                <div className="book-card-overlay">
                  <span className={`status-badge status-${book.status}`}>{STATUS_LABELS[book.status]}</span>
                </div>
              </div>
              <div className="book-card-info">
                <h3 className="book-card-title">{book.title}</h3>
                <p className="book-card-author">{book.author}</p>
                <div className="book-card-progress">
                  <div className="progress-bar-bg">
                    <div className="progress-bar-fill" style={{ width: `${book.totalPages ? (book.uploadedPages / book.totalPages) * 100 : 0}%` }} />
                  </div>
                  <span className="progress-text">{book.uploadedPages}/{book.totalPages}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="pagination">
          <button className="btn-secondary" disabled={currentPage === 1} onClick={() => setCurrentPage(p => p - 1)}>上一页</button>
          <span className="pagination-info">第 {currentPage} / {totalPages} 页</span>
          <button className="btn-secondary" disabled={currentPage === totalPages} onClick={() => setCurrentPage(p => p + 1)}>下一页</button>
        </div>
      )}

      {/* Create Book Modal */}
      {showCreateModal && (
        <div className="modal-overlay" onClick={e => { if (e.target === e.currentTarget) setShowCreateModal(false) }}>
          <div className="modal">
            <h2 className="modal-title">创建新书籍</h2>
            <form onSubmit={e => { e.preventDefault(); handleCreateBook() }} className="modal-form">
              <div className="modal-field">
                <label>书名</label>
                <input type="text" placeholder="输入书籍标题" value={newBook.title} onChange={e => setNewBook(b => ({ ...b, title: e.target.value }))} required />
              </div>
              <div className="modal-field">
                <label>作者</label>
                <input type="text" placeholder="输入作者姓名" value={newBook.author} onChange={e => setNewBook(b => ({ ...b, author: e.target.value }))} required />
              </div>
              <div className="modal-field">
                <label>ISBN (可选)</label>
                <input type="text" placeholder="输入ISBN编号" value={newBook.isbn} onChange={e => setNewBook(b => ({ ...b, isbn: e.target.value }))} />
              </div>
              <div className="modal-field">
                <label>预计总页数</label>
                <input type="number" placeholder="输入预计页数" value={newBook.totalPages} onChange={e => setNewBook(b => ({ ...b, totalPages: Number(e.target.value) }))} required />
              </div>
            </form>
            <div className="modal-footer">
              <button className="btn-secondary" onClick={() => setShowCreateModal(false)}>取消</button>
              <button className="btn-primary" disabled={creating} onClick={handleCreateBook}>
                {creating ? '创建中...' : '创建书籍'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
