// web/src/features/auth/pages/LoginPage/LoginPage.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuthStore } from '@/features/auth/store'
import { useToastStore } from '@/shared/stores/toast'
import { BookOpen, ArrowLeft, Mail, Link as LinkIcon, Shield } from 'lucide-react'
import type { OAuthProvider } from '@/features/auth/types'
import './LoginPage.css'

const ALL_OAUTH_PROVIDERS: { id: OAuthProvider; name: string }[] = [
  { id: 'github', name: 'GitHub' },
  { id: 'gitee', name: 'Gitee' },
  { id: 'google', name: 'Google' },
  { id: 'wechat', name: 'WeChat' },
]

export default function LoginPage() {
  const navigate = useNavigate()
  const auth = useAuthStore()
  const toast = useToastStore(s => s.add)

  const [activeTab, setActiveTab] = useState<'email' | 'oauth'>('email')
  const [step, setStep] = useState(1)
  const [email, setEmail] = useState('')
  const [codeDigits, setCodeDigits] = useState(['', '', '', '', '', ''])
  const [isLoading, setIsLoading] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [countdown, setCountdown] = useState(0)
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [showOAuthModal, setShowOAuthModal] = useState(false)
  const [oauthLoading, setOauthLoading] = useState<Record<string, boolean>>({})

  const codeInputs = useRef<(HTMLInputElement | null)[]>([])
  const oauthWindowRef = useRef<Window | null>(null)

  const oauthProviders = ALL_OAUTH_PROVIDERS.filter(p => auth.isProviderConfigured(p.id))

  useEffect(() => {
    const init = async () => {
      if (!auth.isAuthenticated()) await auth.initialize()
      if (auth.isAuthenticated()) { navigate('/library'); return }
      await auth.loadConfig()
    }
    init()

    const handleMsg = (event: MessageEvent) => {
      if (event.origin !== window.location.origin) return
      if (event.data.type === 'oauth_callback') {
        handleOAuthCallback(event.data.provider, event.data.code, event.data.state)
      }
    }
    window.addEventListener('message', handleMsg)
    return () => {
      window.removeEventListener('message', handleMsg)
      if (oauthWindowRef.current && !oauthWindowRef.current.closed) oauthWindowRef.current.close()
    }
  }, [])

  useEffect(() => {
    if (!auth.isEmailEnabled() && auth.isOAuthEnabled()) setActiveTab('oauth')
  }, [auth.isEmailEnabled, auth.isOAuthEnabled])

  useEffect(() => {
    if (countdown <= 0) return
    const t = setInterval(() => setCountdown(c => { if (c <= 1) { clearInterval(t); return 0 } return c - 1 }), 1000)
    return () => clearInterval(t)
  }, [countdown])

  const handleCodeInput = useCallback(async (index: number, e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value
    if (!/^\d*$/.test(value)) { e.target.value = ''; return }
    const newDigits = [...codeDigits]
    newDigits[index] = value.slice(-1)
    setCodeDigits(newDigits)
    if (value && index < 5) codeInputs.current[index + 1]?.focus()
    if (newDigits.every(d => d !== '')) {
      setErrors(prev => ({ ...prev, code: '' }))
      submitLogin(newDigits)
    }
  }, [codeDigits])

  const handleCodeKeydown = useCallback((index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Backspace') {
      if (!(e.target as HTMLInputElement).value && index > 0) codeInputs.current[index - 1]?.focus()
      else { const nd = [...codeDigits]; nd[index] = ''; setCodeDigits(nd) }
    }
    if (e.key === 'ArrowLeft' && index > 0) { e.preventDefault(); codeInputs.current[index - 1]?.focus() }
    if (e.key === 'ArrowRight' && index < 5) { e.preventDefault(); codeInputs.current[index + 1]?.focus() }
  }, [codeDigits])

  const handleCodePaste = useCallback((e: React.ClipboardEvent) => {
    e.preventDefault()
    const digits = (e.clipboardData.getData('text') || '').replace(/\D/g, '').slice(0, 6)
    const newDigits = [...codeDigits]
    for (let i = 0; i < digits.length; i++) newDigits[i] = digits[i] ?? ''
    setCodeDigits(newDigits)
    codeInputs.current[Math.min(digits.length, 5)]?.focus()
    if (newDigits.every(d => d !== '')) submitLogin(newDigits)
  }, [codeDigits])

  const submitLogin = async (digits: string[]) => {
    const codeValue = digits.join('')
    if (codeValue.length !== 6 || !/^\d{6}$/.test(codeValue)) {
      setErrors(prev => ({ ...prev, code: '请输入完整的 6 位验证码' }))
      return
    }
    setIsSubmitting(true)
    const success = await auth.login({ email, code: codeValue })
    setIsSubmitting(false)
    if (success) {
      toast('success', '登录成功')
      setTimeout(() => navigate('/library'), 500)
    } else {
      setErrors(prev => ({ ...prev, code: auth.error || '登录失败' }))
      setCodeDigits(['', '', '', '', '', ''])
      setTimeout(() => codeInputs.current[0]?.focus(), 50)
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setErrors({})
    if (step === 1) {
      if (!email) { setErrors({ email: '请输入邮箱地址' }); return }
      if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) { setErrors({ email: '请输入有效的邮箱地址' }); return }
      setIsLoading(true)
      const ok = await auth.sendCode({ email, type: 'login' })
      setIsLoading(false)
      if (ok) {
        setStep(2)
        setCountdown(60)
        toast('success', '验证码已发送')
        setTimeout(() => codeInputs.current[0]?.focus(), 50)
      } else {
        setErrors({ email: auth.error || '发送失败' })
      }
    }
  }

  const handleResend = async () => {
    const ok = await auth.sendCode({ email, type: 'login' })
    if (ok) {
      toast('success', '验证码已重新发送')
      setCountdown(60)
      setCodeDigits(['', '', '', '', '', ''])
      setErrors(prev => ({ ...prev, code: '' }))
      setTimeout(() => codeInputs.current[0]?.focus(), 50)
    } else {
      toast('error', auth.error || '发送失败')
    }
  }

  const handleOAuthLogin = async (provider: OAuthProvider) => {
    setOauthLoading(prev => ({ ...prev, [provider]: true }))
    try {
      const redirectUri = `${window.location.origin}/auth/${provider}/callback`
      const result = await auth.getOAuthAuthorizeUrl(provider, redirectUri)
      if (!result?.url) { toast('error', auth.error || '获取授权链接失败'); return }
      localStorage.setItem('oauth_state', result.state)
      setShowOAuthModal(true)
      oauthWindowRef.current = window.open(result.url, 'oauth', 'width=600,height=700,scrollbars=yes')
      if (!oauthWindowRef.current) { toast('error', '弹窗被浏览器阻止，请允许弹窗后重试'); setShowOAuthModal(false); return }
      const checkPopup = setInterval(() => {
        if (oauthWindowRef.current?.closed) { clearInterval(checkPopup); setShowOAuthModal(false); setOauthLoading(prev => ({ ...prev, [provider]: false })) }
      }, 500)
      setTimeout(() => { if (oauthWindowRef.current && !oauthWindowRef.current.closed) { oauthWindowRef.current.close(); setShowOAuthModal(false); toast('error', '授权超时，请稍后再试') } }, 120000)
    } catch { setShowOAuthModal(false); toast('error', '获取授权链接失败') }
    finally { setOauthLoading(prev => ({ ...prev, [provider]: false })) }
  }

  const oauthProcessingRef = useRef(false)
  const handleOAuthCallback = async (provider: OAuthProvider, code: string, state: string) => {
    if (oauthProcessingRef.current) return
    oauthProcessingRef.current = true
    const savedState = localStorage.getItem('oauth_state')
    localStorage.removeItem('oauth_state')
    if (state !== savedState) { toast('error', '授权验证失败：状态不匹配'); oauthProcessingRef.current = false; return }
    const success = await auth.oauthCallback(provider, code, state)
    if (success) { toast('success', '登录成功'); setShowOAuthModal(false); setTimeout(() => navigate('/library'), 500) }
    else { toast('error', auth.error || 'OAuth 登录失败'); oauthProcessingRef.current = false }
    setShowOAuthModal(false)
  }

  return (
    <div className="auth-page">
      {/* Left Brand Section */}
      <div className="auth-brand">
        <div className="brand-content">
          <Link to="/" className="brand-logo">
            <BookOpen size={32} />
            <span className="logo-text">iBookFS</span>
          </Link>
          <h1 className="brand-title">欢迎回来</h1>
          <p className="brand-description">继续管理你的数字藏书，让知识触手可及</p>
          <div className="brand-quote">
            <p className="quote-text">"iBookFS 让我的书籍管理变得如此简单，支持多种登录方式，体验非常流畅。"</p>
            <div className="quote-author">
              <div className="author-avatar">张</div>
              <div>
                <p className="author-name">张明</p>
                <p className="author-title">独立研究者</p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Right Form Section */}
      <div className="auth-form-container">
        <div className="auth-form-wrapper">
          <Link to="/" className="back-link">
            <ArrowLeft size={16} />
            返回首页
          </Link>

          <div className="form-header">
            <h2 className="form-title">登录账号</h2>
            <p className="form-subtitle">选择您喜欢的登录方式</p>
          </div>

          {/* Tab Switcher */}
          {auth.isEmailEnabled() && auth.isOAuthEnabled() && (
            <div className="auth-tabs">
              <button className={`auth-tab ${activeTab === 'email' ? 'active' : ''}`} onClick={() => setActiveTab('email')}>
                <Mail size={18} /> 邮箱登录
              </button>
              <button className={`auth-tab ${activeTab === 'oauth' ? 'active' : ''}`} onClick={() => setActiveTab('oauth')}>
                <LinkIcon size={18} /> 第三方登录
              </button>
            </div>
          )}

          {/* Email Login Form */}
          {activeTab === 'email' && (
            <div className="auth-form-content">
              <form className="auth-form" onSubmit={handleSubmit}>
                <div className="form-group">
                  <label className="form-label">邮箱地址</label>
                  <div className="input-wrapper">
                    <input
                      type="email"
                      className={`form-input ${errors.email ? 'error' : email ? 'success' : ''}`}
                      placeholder="your@email.com"
                      value={email}
                      onChange={e => setEmail(e.target.value)}
                      disabled={step === 2}
                      required
                      autoComplete="email"
                    />
                    <Mail className="input-icon" size={20} />
                  </div>
                  {errors.email && <span className="form-error">{errors.email}</span>}
                </div>

                {step === 2 && (
                  <div className="form-group">
                    <label className="form-label">验证码</label>
                    <div className="code-digits-container">
                      {[0, 1, 2, 3, 4, 5].map(index => (
                        <input
                          key={index}
                          ref={el => { codeInputs.current[index] = el }}
                          type="text"
                          inputMode="numeric"
                          className={`code-digit-input ${errors.code ? 'error' : codeDigits.join('').length === 6 ? 'success' : ''}`}
                          maxLength={1}
                          value={codeDigits[index]}
                          onChange={e => handleCodeInput(index, e)}
                          onKeyDown={e => handleCodeKeydown(index, e)}
                          onPaste={handleCodePaste}
                          autoComplete="one-time-code"
                        />
                      ))}
                    </div>
                    <span className="form-hint">验证码已发送至 <strong>{email}</strong></span>
                    {errors.code && <span className="form-error">{errors.code}</span>}
                  </div>
                )}

                {step === 1 && (
                  <button type="submit" className="button-primary button-lg button-full" disabled={isLoading}>
                    {!isLoading ? <span>发送验证码</span> : (
                      <span className="btn-loading">
                        <svg className="spinner" width="20" height="20" viewBox="0 0 20 20">
                          <circle cx="10" cy="10" r="8" stroke="currentColor" strokeWidth="2" fill="none" opacity="0.25" />
                          <path d="M10 2a8 8 0 018 8" stroke="currentColor" strokeWidth="2" fill="none" />
                        </svg>
                        处理中...
                      </span>
                    )}
                  </button>
                )}

                {step === 2 && !isSubmitting && (
                  <button type="button" className="resend-button button-lg button-full" disabled={countdown > 0 || isLoading} onClick={handleResend}>
                    {countdown > 0 ? `${countdown}s 后重新发送` : '重新发送验证码'}
                  </button>
                )}

                {step === 2 && isSubmitting && (
                  <div className="submitting-state">
                    <svg className="spinner" width="24" height="24" viewBox="0 0 24 24">
                      <circle cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="3" fill="none" opacity="0.25" />
                      <path d="M12 2a10 10 0 0110 10" stroke="currentColor" strokeWidth="3" fill="none" />
                    </svg>
                    <span>验证中...</span>
                  </div>
                )}
              </form>
            </div>
          )}

          {/* OAuth Login */}
          {activeTab === 'oauth' && (
            <div className="oauth-content">
              <p className="oauth-description">使用您的第三方账号快速登录</p>
              <div className="oauth-buttons">
                {oauthProviders.map(provider => (
                  <button key={provider.id} className="oauth-button" disabled={oauthLoading[provider.id]} onClick={() => handleOAuthLogin(provider.id)}>
                    使用 {provider.name} 登录
                  </button>
                ))}
              </div>
              <div className="oauth-hint">
                <Shield size={16} />
                <span>我们尊重您的隐私，不会获取不必要的权限</span>
              </div>
            </div>
          )}

          <div className="divider"><span>或</span></div>

          <div className="form-footer">
            <p className="footer-text">
              还没有账号？
              <Link to="/register" className="footer-link">立即注册</Link>
            </p>
          </div>

          <p className="privacy-notice">
            登录即表示您同意我们的
            <a href="/terms">服务条款</a>
            和
            <a href="/privacy">隐私政策</a>
          </p>
        </div>
      </div>

      {/* OAuth Callback Modal */}
      {showOAuthModal && (
        <div className="oauth-modal-overlay" onClick={e => { if (e.target === e.currentTarget) setShowOAuthModal(false) }}>
          <div className="oauth-modal">
            <div className="oauth-modal-content">
              <div className="oauth-modal-icon">
                <svg className="spinner" width="48" height="48" viewBox="0 0 48 48">
                  <circle cx="24" cy="24" r="20" stroke="currentColor" strokeWidth="3" fill="none" opacity="0.25" />
                  <path d="M24 4a20 20 0 0120 20" stroke="currentColor" strokeWidth="3" fill="none" />
                </svg>
              </div>
              <h3 className="oauth-modal-title">正在连接...</h3>
              <p className="oauth-modal-description">请在新窗口中完成授权</p>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// web/src/pages/LoginPage.vue
<template>
  <div class="auth-page">
    <!-- Left Brand Section -->
    <div class="auth-brand">
      <div class="brand-content">
        <router-link to="/" class="brand-logo">
          <BookOpen :size="32" />
          <span class="logo-text">iBookFS</span>
        </router-link>

        <h1 class="brand-title">欢迎回来</h1>
        <p class="brand-description">继续管理你的数字藏书，让知识触手可及</p>

        <div class="brand-quote">
          <p class="quote-text">
            "iBookFS 让我的书籍管理变得如此简单，OCR 功能更是节省了大量时间。"
          </p>
          <div class="quote-author">
            <div class="author-avatar">张</div>
            <div>
              <p class="author-name">张明</p>
              <p class="author-title">独立研究者</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Right Form Section -->
    <div class="auth-form-container">
      <div class="auth-form-wrapper">
        <!-- Back to Home -->
        <router-link to="/" class="back-link">
          <ArrowLeft :size="16" />
          返回首页
        </router-link>

        <!-- Form Header -->
        <div class="form-header">
          <h2 class="form-title">登录账号</h2>
          <p class="form-subtitle">使用邮箱验证码快速登录</p>
        </div>

        <!-- Login Form -->
        <form class="auth-form" @submit.prevent="handleSubmit">
          <!-- Email Input -->
          <div class="form-group">
            <label for="email" class="form-label">邮箱地址</label>
            <div class="input-wrapper">
              <input
                id="email"
                v-model="email"
                type="email"
                class="form-input"
                :class="{ error: errors.email, success: !errors.email && email }"
                placeholder="your@email.com"
                :disabled="step === 2"
                required
                autocomplete="email"
              />
              <Mail class="input-icon" :size="20" />
            </div>
            <span v-if="errors.email" class="form-error">{{ errors.email }}</span>
          </div>

          <!-- Verification Code Input -->
          <div v-show="step === 2" class="form-group">
            <label for="code" class="form-label">验证码</label>
            <div class="code-input-wrapper">
              <input
                id="code"
                v-model="code"
                type="text"
                class="form-input code-input"
                :class="{ error: errors.code, success: !errors.code && code }"
                placeholder="输入 6 位验证码"
                maxlength="6"
                required
                autocomplete="one-time-code"
              />
              <button
                type="button"
                class="resend-btn"
                :disabled="countdown > 0"
                @click="handleResend"
              >
                {{ countdown > 0 ? `${countdown}s` : '重新发送' }}
              </button>
            </div>
            <span class="form-hint">
              验证码已发送至 <strong>{{ email }}</strong>
            </span>
            <span v-if="errors.code" class="form-error">{{ errors.code }}</span>
          </div>

          <!-- Demo Hint -->
          <div v-if="step === 2" class="demo-hint">
            <Info :size="16" />
            <span>演示模式：验证码为 <strong>123456</strong></span>
          </div>

          <!-- Submit Button -->
          <button type="submit" class="button-primary button-lg button-full" :disabled="isLoading">
            <span v-if="!isLoading" class="btn-text">{{ step === 1 ? '发送验证码' : '登录' }}</span>
            <span v-else class="btn-loading">
              <svg class="spinner" width="20" height="20" viewBox="0 0 20 20">
                <circle cx="10" cy="10" r="8" stroke="currentColor" stroke-width="2" fill="none" opacity="0.25" />
                <path d="M10 2a8 8 0 018 8" stroke="currentColor" stroke-width="2" fill="none" />
              </svg>
              处理中...
            </span>
          </button>
        </form>

        <!-- Divider -->
        <div class="divider">
          <span>或</span>
        </div>

        <!-- Register Link -->
        <div class="form-footer">
          <p class="footer-text">
            还没有账号？
            <router-link to="/register" class="footer-link">立即注册</router-link>
          </p>
        </div>

        <!-- Privacy Notice -->
        <p class="privacy-notice">
          登录即表示您同意我们的
          <a href="/terms">服务条款</a>
          和
          <a href="/privacy">隐私政策</a>
        </p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { BookOpen, ArrowLeft, Mail, Info } from 'lucide-vue-next'
import { sendCode, login } from '@/api'
import { useToastStore } from '@/stores/toast'

const router = useRouter()
const toastStore = useToastStore()

const email = ref('')
const code = ref('')
const step = ref(1)
const isLoading = ref(false)
const countdown = ref(0)
const errors = ref<Record<string, string>>({})

let countdownTimer: ReturnType<typeof setInterval> | null = null

const validateEmail = (): boolean => {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  if (!email.value) {
    errors.value.email = '请输入邮箱地址'
    return false
  }
  if (!emailRegex.test(email.value)) {
    errors.value.email = '请输入有效的邮箱地址'
    return false
  }
  errors.value.email = ''
  return true
}

const validateCode = (): boolean => {
  if (!code.value) {
    errors.value.code = '请输入验证码'
    return false
  }
  if (!/^\d{6}$/.test(code.value)) {
    errors.value.code = '验证码必须是 6 位数字'
    return false
  }
  errors.value.code = ''
  return true
}

const startCountdown = () => {
  countdown.value = 60
  countdownTimer = setInterval(() => {
    countdown.value--
    if (countdown.value <= 0) {
      if (countdownTimer) clearInterval(countdownTimer)
    }
  }, 1000)
}

const handleResend = async () => {
  const response = await sendCode({ email: email.value, type: 'login' })
  if (response.success) {
    toastStore.success('验证码已重新发送')
    startCountdown()
  } else {
    toastStore.error(response.message || '发送失败')
  }
}

const handleSubmit = async () => {
  errors.value = {}

  if (step.value === 1) {
    if (!validateEmail()) return

    isLoading.value = true
    const response = await sendCode({ email: email.value, type: 'login' })
    isLoading.value = false

    if (response.success) {
      step.value = 2
      startCountdown()
      toastStore.success('验证码已发送')
    } else {
      errors.value.email = response.message || '发送失败'
    }
  } else {
    if (!validateCode()) return

    isLoading.value = true
    const response = await login({ email: email.value, code: code.value })
    isLoading.value = false

    if (response.success) {
      toastStore.success('登录成功')
      setTimeout(() => {
        router.push('/library')
      }, 500)
    } else {
      errors.value.code = response.message || '登录失败'
    }
  }
}
</script>

<style scoped>
.auth-page {
  min-height: 100vh;
  display: grid;
  grid-template-columns: 40% 60%;
  background: var(--bg-primary);
}

/* Left Brand Section */
.auth-brand {
  position: relative;
  background: linear-gradient(135deg, var(--color-accent) 0%, #a6624a 100%);
  color: white;
  padding: var(--space-8);
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
}

.auth-brand::before {
  content: '';
  position: absolute;
  top: -50%;
  right: -20%;
  width: 600px;
  height: 600px;
  background: radial-gradient(circle, rgba(255, 255, 255, 0.1) 0%, transparent 70%);
  border-radius: 50%;
  animation: float 20s ease-in-out infinite;
}

.auth-brand::after {
  content: '';
  position: absolute;
  bottom: -30%;
  left: -10%;
  width: 400px;
  height: 400px;
  background: radial-gradient(circle, rgba(255, 255, 255, 0.08) 0%, transparent 70%);
  border-radius: 50%;
  animation: float 15s ease-in-out infinite reverse;
}

.brand-content {
  position: relative;
  z-index: 1;
  max-width: 480px;
  width: 100%;
}

.brand-logo {
  display: inline-flex;
  align-items: center;
  gap: var(--space-2);
  font-family: var(--font-display);
  font-size: var(--text-xl);
  font-weight: var(--font-weight-bold);
  color: white;
  text-decoration: none;
  margin-bottom: var(--space-8);
  transition: opacity var(--duration-fast) var(--ease-out);
}

.brand-logo:hover {
  opacity: 0.9;
}

.logo-text {
  margin-left: var(--space-2);
}

.brand-title {
  font-size: var(--text-4xl);
  font-weight: var(--font-weight-bold);
  line-height: 1.2;
  margin-bottom: var(--space-4);
  color: white;
}

.brand-description {
  font-size: var(--text-lg);
  line-height: 1.6;
  color: rgba(255, 255, 255, 0.9);
  margin-bottom: var(--space-8);
}

.brand-quote {
  background: rgba(255, 255, 255, 0.1);
  backdrop-filter: blur(10px);
  border-radius: var(--radius-lg);
  padding: var(--space-5);
  border: 1px solid rgba(255, 255, 255, 0.2);
}

.quote-text {
  font-size: var(--text-base);
  line-height: 1.6;
  font-style: italic;
  color: rgba(255, 255, 255, 0.95);
  margin-bottom: var(--space-4);
}

.quote-author {
  display: flex;
  align-items: center;
  gap: var(--space-3);
}

.author-avatar {
  width: 40px;
  height: 40px;
  border-radius: var(--radius-full);
  background: rgba(255, 255, 255, 0.3);
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: var(--font-weight-semibold);
  border: 2px solid rgba(255, 255, 255, 0.3);
}

.author-name {
  font-size: var(--text-sm);
  font-weight: var(--font-weight-semibold);
  color: white;
}

.author-title {
  font-size: var(--text-xs);
  color: rgba(255, 255, 255, 0.8);
}

/* Right Form Section */
.auth-form-container {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: var(--space-8);
  background: var(--bg-primary);
}

.auth-form-wrapper {
  width: 100%;
  max-width: 440px;
  animation: fadeInUp 0.6s var(--ease-out);
}

.back-link {
  display: inline-flex;
  align-items: center;
  gap: var(--space-2);
  font-size: var(--text-sm);
  color: var(--color-ink-light);
  margin-bottom: var(--space-8);
  text-decoration: none;
  transition: color var(--duration-fast) var(--ease-out);
}

.back-link:hover {
  color: var(--color-accent);
}

.form-header {
  margin-bottom: var(--space-8);
}

.form-title {
  font-size: var(--text-3xl);
  font-weight: var(--font-weight-bold);
  margin-bottom: var(--space-2);
  color: var(--color-ink);
}

.form-subtitle {
  font-size: var(--text-base);
  color: var(--color-ink-light);
}

/* Form Styles */
.auth-form {
  display: flex;
  flex-direction: column;
  gap: var(--space-5);
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: var(--space-2);
}

.form-label {
  font-size: var(--text-sm);
  font-weight: var(--font-weight-medium);
  color: var(--color-ink);
}

.input-wrapper {
  position: relative;
}

.form-input {
  width: 100%;
  padding: var(--space-3) var(--space-4);
  font-size: var(--text-base);
  color: var(--color-ink);
  background: var(--bg-elevated);
  border: 1.5px solid var(--border-medium);
  border-radius: var(--radius-md);
  transition: all var(--duration-fast) var(--ease-out);
}

.input-wrapper .form-input {
  padding-right: var(--space-10);
}

.form-input::placeholder {
  color: var(--color-ink-light);
}

.form-input:focus {
  outline: none;
  border-color: var(--color-accent);
  box-shadow: 0 0 0 3px rgba(193, 123, 92, 0.2);
}

.form-input:disabled {
  opacity: 0.6;
  cursor: not-allowed;
  background: var(--bg-secondary);
}

.form-input.error {
  border-color: var(--color-error);
}

.form-input.error:focus {
  box-shadow: 0 0 0 3px rgba(184, 92, 92, 0.2);
}

.form-input.success {
  border-color: var(--color-success);
}

.input-icon {
  position: absolute;
  right: var(--space-4);
  top: 50%;
  transform: translateY(-50%);
  color: var(--color-ink-light);
  pointer-events: none;
}

/* Code Input */
.code-input-wrapper {
  position: relative;
  display: flex;
  gap: var(--space-2);
}

.code-input {
  font-family: var(--font-mono);
  font-size: var(--text-lg);
  letter-spacing: 0.5em;
  text-align: center;
  flex: 1;
}

.resend-btn {
  padding: var(--space-3) var(--space-4);
  font-size: var(--text-sm);
  font-weight: var(--font-weight-medium);
  color: var(--color-accent);
  background: var(--bg-secondary);
  border: 1.5px solid var(--border-medium);
  border-radius: var(--radius-md);
  white-space: nowrap;
  cursor: pointer;
  transition: all var(--duration-fast) var(--ease-out);
}

.resend-btn:hover:not(:disabled) {
  background: var(--color-accent-light);
  border-color: var(--color-accent);
}

.resend-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

/* Hint and Error */
.form-hint {
  font-size: var(--text-xs);
  color: var(--color-ink-light);
}

.form-hint strong {
  color: var(--color-ink);
  font-weight: var(--font-weight-medium);
}

.form-error {
  font-size: var(--text-xs);
  color: var(--color-error);
}

.demo-hint {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  padding: var(--space-3);
  background: var(--bg-secondary);
  border-radius: var(--radius-md);
  font-size: var(--text-sm);
  color: var(--color-ink-light);
}

.demo-hint strong {
  color: var(--color-accent);
}

/* Button */
.button-full {
  width: 100%;
}

.button-primary {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: var(--space-3) var(--space-6);
  font-size: var(--text-base);
  font-weight: var(--font-weight-medium);
  color: white;
  background: var(--color-accent);
  border: none;
  border-radius: var(--radius-md);
  cursor: pointer;
  transition: all var(--duration-fast) var(--ease-out);
}

.button-primary:hover:not(:disabled) {
  background: #a6624a;
  transform: translateY(-1px);
}

.button-primary:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}

.button-lg {
  padding: var(--space-4) var(--space-6);
}

.btn-loading {
  display: flex;
  align-items: center;
  gap: var(--space-2);
}

.spinner {
  animation: spin 0.8s linear infinite;
}

/* Divider */
.divider {
  position: relative;
  text-align: center;
  margin: var(--space-6) 0;
}

.divider::before {
  content: '';
  position: absolute;
  top: 50%;
  left: 0;
  right: 0;
  height: 1px;
  background: var(--border-subtle);
}

.divider span {
  position: relative;
  display: inline-block;
  padding: 0 var(--space-4);
  font-size: var(--text-sm);
  color: var(--color-ink-light);
  background: var(--bg-primary);
}

/* Footer */
.form-footer {
  text-align: center;
}

.footer-text {
  font-size: var(--text-base);
  color: var(--color-ink-light);
}

.footer-link {
  color: var(--color-accent);
  font-weight: var(--font-weight-medium);
  text-decoration: none;
  transition: color var(--duration-fast) var(--ease-out);
}

.footer-link:hover {
  color: #a6624a;
}

.privacy-notice {
  margin-top: var(--space-6);
  padding-top: var(--space-6);
  border-top: 1px solid var(--border-subtle);
  font-size: var(--text-xs);
  color: var(--color-ink-light);
  text-align: center;
  line-height: 1.6;
}

.privacy-notice a {
  color: var(--color-ink-light);
  text-decoration: underline;
}

/* Animations */
@keyframes float {
  0%,
  100% {
    transform: translateY(0) rotate(0deg);
  }
  50% {
    transform: translateY(-20px) rotate(5deg);
  }
}

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

/* Responsive */
@media (max-width: 1024px) {
  .auth-page {
    grid-template-columns: 1fr;
  }

  .auth-brand {
    display: none;
  }

  .auth-form-container {
    padding: var(--space-6) var(--space-4);
  }
}

@media (max-width: 640px) {
  .form-title {
    font-size: var(--text-2xl);
  }

  .code-input-wrapper {
    flex-direction: column;
  }

  .resend-btn {
    width: 100%;
  }
}
</style>
